":construction: Карты":
- changed-files:
  - any-glob-to-any-file: "Resources/Maps/**/*.yml"

":art: Спрайты":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.rsi/*.png"
    - "**/*.rsi/*.json"

":iphone: Интерфейс":
- changed-files:
  - any-glob-to-any-file: "**/*.xaml*"

":chart_with_upwards_trend: C#":
- changed-files:
  - any-glob-to-any-file: "**/*.cs"

":art: Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

":musical_note: Аудио":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

":chart_with_downwards_trend: Без C#":
- changed-files:
  - all-globs-to-all-files: "!**/*.cs"

":book: Документация":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.xml"
    - "**/*.md"

":page_facing_up: Локализация":
- changed-files:
  - any-glob-to-any-file: "Resources/Locale/**/*.ftl"

":baby_chick: Прототипы":
- all:
  - changed-files:
    - any-glob-to-any-file: "**/*.yml"
    - all-globs-to-any-file:
      - "!Resources/Maps/**/*.yml"
      - "!Resources/Prototypes/Maps/**/*.yml"

":surfer: Миграция Файлов":
- changed-files:
  - any-glob-to-any-file: "Content.Server.Database/Migrations/**/*.cs"

":alien: SCP-Foundation":
- changed-files:
  - all-globs-to-all-files: "!**/_SCP/**"
