using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._SCP.Guestbook.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._SCP.Guestbook;

[GenerateTypedNameReferences]
public sealed partial class GuestbookWindow : FancyWindow
{
    public event Action<NetEntity, string>? OnRename;
    public event Action<NetEntity>? OnDelete;

    private NetEntity? _renameTarget;

    private sealed record EntryData(NetEntity Target, string GivenName);

    public GuestbookWindow()
    {
        RobustXamlLoader.Load(this);

        EntriesList.OnItemSelected += _ => UpdateButtons();
        EntriesList.OnItemDeselected += _ => UpdateButtons();

        RenameButton.OnPressed += _ => BeginRename();
        DeleteButton.OnPressed += _ => BeginDelete();

        ConfirmButton.OnPressed += _ => ConfirmRename();
        CancelButton.OnPressed += _ => HideRenamePanel();
    }

    public void UpdateState(GuestbookBuiState state)
    {
        Title = Loc.GetString("guestbook-window-title", ("name", state.OwnerName));

        EntriesList.Clear();

        foreach (var entry in state.Entries)
        {
            var item = EntriesList.AddItem(entry.GivenName);
            item.Metadata = new EntryData(entry.Target, entry.GivenName);
        }

        UpdateButtons();
    }

    private void UpdateButtons()
    {
        var hasSelection = EntriesList.GetSelected().Any();
        RenameButton.Disabled = !hasSelection;
        DeleteButton.Disabled = !hasSelection;
    }

    private EntryData? GetSelectedEntry()
    {
        var selected = EntriesList.GetSelected().FirstOrDefault();
        return selected?.Metadata as EntryData;
    }

    private void BeginRename()
    {
        var entry = GetSelectedEntry();
        if (entry == null)
            return;

        _renameTarget = entry.Target;
        InputPrompt.Text = Loc.GetString("guestbook-rename-prompt");
        NameInput.Text = entry.GivenName;
        InputPanel.Visible = true;
        NameInput.GrabKeyboardFocus();
    }

    private void BeginDelete()
    {
        var entry = GetSelectedEntry();
        if (entry == null)
            return;

        OnDelete?.Invoke(entry.Target);
    }

    private void HideRenamePanel()
    {
        InputPanel.Visible = false;
        _renameTarget = null;
    }

    private void ConfirmRename()
    {
        if (_renameTarget is not { } target)
            return;

        var name = NameInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        OnRename?.Invoke(target, name);
        HideRenamePanel();
    }
}
