using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._SCP.Guestbook;

[GenerateTypedNameReferences]
public sealed partial class GuestbookNameInputWindow : FancyWindow
{
    public NetEntity Target { get; private set; }

    public event Action<NetEntity, string>? OnConfirm;

    public GuestbookNameInputWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Confirm();
        CancelButton.OnPressed += _ => Close();
    }

    public void SetTarget(NetEntity target, string realName)
    {
        Target = target;
        Prompt.Text = Loc.GetString("guestbook-add-prompt", ("target", realName));
        NameInput.Text = string.Empty;
        NameInput.GrabKeyboardFocus();
    }

    private void Confirm()
    {
        var name = NameInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        OnConfirm?.Invoke(Target, name);
        Close();
    }
}
