- type: entity
  id: SCPBaseDoor
  parent: BaseStructure
  name: door
  abstract: true
  description: It opens, it closes, and maybe crushes you.
  placement:
    mode: SnapgridCenter
  components:
  - type: Anchorable
    flags:
    - Anchorable
  - type: Rotatable
  - type: Airtight
  - type: AccessReader
    containerAccessProvider: board
  - type: ApcPowerReceiver
    powerLoad: 20
  - type: ExtensionCableReceiver
  - type: Sprite
    sprite: _SCP/Structures/Doors/default.rsi
    layers:
    - state: wall
    - state: closed
      map: ["enum.DoorVisualLayers.Base"]
    - state: closed_unlit
      shader: unshaded
      map: ["enum.DoorVisualLayers.BaseUnlit"]
      visible: false
    - state: welded
      map: ["enum.WeldableLayers.BaseWelded"]
    - state: bolted_unlit
      shader: unshaded
      map: ["enum.DoorVisualLayers.BaseBolted"]
    - state: emergency_unlit
      map: ["enum.DoorVisualLayers.BaseEmergencyAccess"]
      shader: unshaded
    - state: panel_open
      map: ["enum.WiresVisualLayers.MaintenancePanel"]
  - type: LayerChangeOnWeld
    unWeldedLayer: AirlockLayer
    weldedLayer: WallLayer
  - type: WiresVisuals
  - type: WiresPanel
  - type: WiresPanelSecurity
  - type: Wires
    boardName: wires-board-name-airlock
    layoutId: Airlock
  - type: Door
    bumpOpen: false
    clickOpen: true
    closeTimeOne: 0.4
    closeTimeTwo: 0.4
    openTimeOne: 0.4
    openTimeTwo: 0.4
    openingAnimationTime: 1.0
    closingAnimationTime: 1.0
    canPry: false
    performCollisionCheck: false
    crushDamage:
      types:
        Blunt: 25
    openSound:
      collection: SCPDoorOpen
    closeSound:
      collection: SCPDoorClose
    denySound:
      path: /Audio/_SCP/Effects/Elevator/elevator_noactive.ogg
  - type: Occluder
  - type: DoorBolt
  - type: Airlock
    autoClose: false
    openUnlitVisible: true
  - type: BlockWeather
  - type: Appearance
  - type: RadiationBlocker
    resistance: 8
  - type: Damageable
    damageModifierSet: StrongMetallic
  - type: Injurable
    damageContainer: StructuralInorganic
  - type: ContainerFill
    containers:
      board: [ DoorElectronics ]
  - type: Construction
    graph: BlastDoor
    node: blastdoor
    containers:
    - board
  - type: StaticPrice
    price: 500
  - type: InteractionOutline
  - type: AnimationPlayer
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49" # don't want this colliding with walls or they won't close
        density: 100
        mask:
        - FullTileMask
        layer:
        - AirlockLayer
  - type: ContainerContainer
    containers:
      board: !type:Container
  - type: NavMapDoor
  - type: Tag
    tags:
    - ForceNoFixRotations # Don't want the fixrotations command to target these
  - type: Weldable
    time: 3
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 500
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
  - type: DoorSignalControl
  - type: DeviceNetwork
    deviceNetId: Wireless
    receiveFrequencyId: BasicDevice
  - type: DeviceLinkSink
    ports:
      - Open
      - Close
      - Toggle
      - DoorBolt
  - type: DeviceLinkSource
    ports:
    - DoorStatus
    lastSignals:
      DoorStatus: false
  - type: IconSmooth
    key: walls
    mode: NoSprite
  - type: UserInterface
    interfaces:
      enum.AiUi.Key:
        type: StationAiBoundUserInterface

- type: entity
  id: SCPDoorSolid
  parent: SCPBaseDoor
  components:
  - type: Sprite
    sprite: _SCP/Structures/Doors/default.rsi
    layers:
    - state: wall
      color: "#7F7F75"
    - state: closed
      map: ["enum.DoorVisualLayers.Base"]
    - state: closed_unlit
      shader: unshaded
      map: ["enum.DoorVisualLayers.BaseUnlit"]
      visible: false
    - state: welded
      map: ["enum.WeldableLayers.BaseWelded"]
    - state: bolted_unlit
      shader: unshaded
      map: ["enum.DoorVisualLayers.BaseBolted"]
    - state: emergency_unlit
      map: ["enum.DoorVisualLayers.BaseEmergencyAccess"]
      shader: unshaded
    - state: panel_open
      map: ["enum.WiresVisualLayers.MaintenancePanel"]

- type: entity
  id: SCPDoorMetal
  parent: SCPBaseDoor
  components:
  - type: Sprite
    sprite: _SCP/Structures/Doors/default.rsi
    layers:
    - state: wall
      color: "#505050"
    - state: closed
      map: ["enum.DoorVisualLayers.Base"]
    - state: closed_unlit
      shader: unshaded
      map: ["enum.DoorVisualLayers.BaseUnlit"]
      visible: false
    - state: welded
      map: ["enum.WeldableLayers.BaseWelded"]
    - state: bolted_unlit
      shader: unshaded
      map: ["enum.DoorVisualLayers.BaseBolted"]
    - state: emergency_unlit
      map: ["enum.DoorVisualLayers.BaseEmergencyAccess"]
      shader: unshaded
    - state: panel_open
      map: ["enum.WiresVisualLayers.MaintenancePanel"]
